### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by Rajdeep1311**
- Added a Basic Program Schedule
- Added a CNCF Logo

### CODE REVIEW

**Comment by Rajdeep1311** [comment]
@onlydole sir please do see to this

**Comment by onlydole** [comment]
Thank you for this, @Rajdeep1311! I'm going to suggest a few edits in some places this week, and then we can get this merged in.

**Comment by Rajdeep1311** [comment]
@onlydole sure sir

**Comment by onlydole** [comment]
Thank you, @Rajdeep1311!

**Pull request merged**
